#!/usr/bin/env bash
#configure a custom 404 page

sudo apt-get update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
chmod -R 755 /var/www
echo 'Hello World!' > /var/www/html/index.html

new_config=\
"server {
        listen 80 default_server;
	error_page 404 /404.html;
	location = /404.html {
		root /var/www/html;
		internal;
	}
        listen [::]:80 default_server;
}
"
echo "Ceci n'est pas une page" > /var/www/html/404.html
echo "$new_config" > /etc/nginx/sites-available/default

if [ "$(pgrep nginx)" -le 0 ];
then
    service nginx start
else
    service nginx restart
fi;
