#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
sudo apt-get -y update
sudo apt-get -y install haproxy

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
# backing up the default settings 
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

echo '
frontend codingverse.tech
        bind *:80
	mode http
        default_backend web_servers

backend web_servers
	mode http
        balance roundrobin
        server 133957-web-01 54.144.150.231:80 check
        server 133957-web-02 18.204.13.57:80 check
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
